### ISSUE TITLE
Nvidia required on the cpu-friendly branch

### ISSUE THREAD

**Issue by ghost** [pangyuteng/virtual-background#6]
I don't have an Nvidia graphics card, but and AMD one, so I built from the `cpu-friendly` branch.

`docker-compose build` worked well (after fixing #4), but `docker-compose up` failed:

```
WARNING: Some networks were defined but are not used by any service: fakecam
Creating network "vbkgd_default" with the default driver
Creating vbkgd_bodypix_1 ... error

ERROR: for vbkgd_bodypix_1  Cannot create container for service bodypix: Unknown runtime specified nvidia

ERROR: for bodypix  Cannot create container for service bodypix: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
```

I saw [the README](https://github.com/pangyuteng/virtual-background/blob/master/README.md) said:

> If this doesn't work and you get something like `ERROR: for vbkgd_bodypix_1 Cannot create container for service bodypix: Unknown runtime specified nvidia` do the steps described [here](https://github.com/NVIDIA/nvidia-docker/issues/1073#issuecomment-532104398) and restart using `docker-compose up`

The solution was supposed to be:

> Replace the line:
> 
> ```
> $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
> ```
> 
> By:
> 
> ```
> $ sudo apt-get update && sudo apt-get install -y nvidia-docker2
> ```

But I hadn't installed any `nvidia-container-*` packages because the README also said earlier:

> (skip if you have no GPU) install nvidia-docker (https://github.com/NVIDIA/nvidia-docker), and `sudo apt install nvidia-container-runtime`

Shouldn't the Nvidia packages not be necessary on the `cpu-friendly` branch?

**Comment by pangyuteng** [comment]
"skip if you have no GPU"
You are correct. If you have no GPU, no need to install nvidia-docker!

**Comment by ghost** [comment]
OK, but somehow it seems it's still required, because I get this:
> ERROR: for vbkgd_bodypix_1  Cannot create container for service bodypix: Unknown runtime specified nvidia

**Comment by pangyuteng** [comment]
I see... I have updated the docker-compose file. please pull from remote cpu-friendly 
https://github.com/pangyuteng/virtual-background/commit/8ff5df5a65ecd4a4fbb17af748754898126b99a4
